# The high-level question category that we are eliciting
@Prompts = new Meteor.Collection("prompts")

# What we present to ask for certain ideas
@Tasks = new Meteor.Collection("tasks")

# Ideas that we use to seed the tasks
@Items = new Meteor.Collection("items")

# Artifacts generated by the prompts
@Interactions = new Meteor.Collection("interaction")
@Responses = new Meteor.Collection("responses")
